[build]
    functions = "functions"
    publish = "build/web"
    command = "npm i && if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web"

[dev]
    functions = "functions"
    functionsPort = 7000